### ISSUE TITLE
Missing required fields exception

### ISSUE THREAD

**Issue by mindzia** [Esri/hadoop-for-geoevent#1]
Hello,
just tried this geoevent output extension. Output fails with exception "missing required fields":
Hadoop cluster is running on other host. Hadoop version 2.4.1

An unexpected error has occurred while receiving messages. Error: Failed on local exception: com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: callId, status; Host Details : local host is: "HBGIS-CSD07/192.168.123.10"; destination host is: "hd-master":8020; .

Failed on local exception: com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: callId, status; Host Details : local host is: "HBGIS-CSD07/192.168.123.10"; destination host is: "hd-master":8020; java.io.IOException: Failed on local exception: com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: callId, status; Host Details : local host is: "HBGIS-CSD07/192.168.123.10"; destination host is: "hd-master":8020; at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:760) at org.apache.hadoop.ipc.Client.call(Client.java:1229) at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:202) at com.sun.proxy.$Proxy84.getFileInfo(Unknown Source)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at sun.reflect.GeneratedMethodAccessor458.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.7.0_76] at java.lang.reflect.Method.invoke(Method.java:606)[:1.7.0_76] at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:164)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:83)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at com.sun.proxy.$Proxy84.getFileInfo(Unknown Source)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:628)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1545)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:805)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at org.apache.hadoop.fs.FileSystem.isFile(FileSystem.java:1393)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at com.esri.geoevent.transport.hdfs.HDFSConnection.checkFileSystemConnection(HDFSConnection.java:108)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at com.esri.geoevent.transport.hdfs.HDFSConnection.send(HDFSConnection.java:94)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at com.esri.geoevent.transport.hdfs.HDFSOutboundTransport.receive(HDFSOutboundTransport.java:150)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at com.esri.ges.manager.stream.internal.OutboundTransportProxy.receive(OutboundTransportProxy.java:42)[327:com.esri.ges.manager.internal-streammanager:10.3.1] at com.esri.ges.manager.stream.internal.OutboundStreamImpl.receive(OutboundStreamImpl.java:202)[327:com.esri.ges.manager.internal-streammanager:10.3.1] at com.esri.ges.adapter.OutboundAdapterBase.receive(OutboundAdapterBase.java:44)[253:com.esri.ges.framework.adapter.adapter-api:10.3.1] at com.esri.ges.adapter.text.TextOutboundAdapter.access$300(TextOutboundAdapter.java:33)[255:com.esri.ges.framework.adapter.text-adapter:10.3.1] at com.esri.ges.adapter.text.TextOutboundAdapter$Worker.performWork(TextOutboundAdapter.java:101)[255:com.esri.ges.framework.adapter.text-adapter:10.3.1] at com.esri.ges.adapter.text.TextOutboundAdapter$Worker.run(TextOutboundAdapter.java:84)[255:com.esri.ges.framework.adapter.text-adapter:10.3.1] Caused by: com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: callId, status at com.google.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:81)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at org.apache.hadoop.ipc.protobuf.RpcPayloadHeaderProtos$RpcResponseHeaderProto$Builder.buildParsed(RpcPayloadHeaderProtos.java:1094)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at org.apache.hadoop.ipc.protobuf.RpcPayloadHeaderProtos$RpcResponseHeaderProto$Builder.access$1300(RpcPayloadHeaderProtos.java:1028)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at org.apache.hadoop.ipc.protobuf.RpcPayloadHeaderProtos$RpcResponseHeaderProto.parseDelimitedFrom(RpcPayloadHeaderProtos.java:986)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at org.apache.hadoop.ipc.Client$Connection.receiveResponse(Client.java:938)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0] at org.apache.hadoop.ipc.Client$Connection.run(Client.java:836)[403:com.esri.geoevent.transport.hdfs-transport:10.3.0]

**Comment by mindzia** [comment]
Recompiled with newer hadoop client version 2.6.0-cdh5.4.4.1
Works.
